version: v.2.3.4
pidfile: ./jobworker.pid
retrystartup: true
useserverconfig: true
centerhost: http://127.0.0.1:8985
websitehost: http://127.0.0.1:8091
cluster:
    hosts: 127.0.0.1:2181
    root: /cloudtask
    device:
    runtime: myCluster
    pulse: 8s
    threshold: 1
api:
    hosts: [":8600"]
    enablecors: true
cache:
    maxjobs: 255
    savedirectory: ./cache
    autoclean: true
    cleaninterval: 30m
    pullrecovery: 300s
logger:
    logfile: ./logs/jobworker.log
    loglevel: error
    logsize: 20971520
...
